### ISSUE TITLE
Lost dependency

### ISSUE THREAD

**Issue by m49n** [jan-vince/smallmessages#3]
![image](https://user-images.githubusercontent.com/15114737/109386675-5145d980-790d-11eb-8513-ce30abdb1c46.png)
trans function available only with this plugin https://octobercms.com/plugin/vojtasvoboda-twigextensions

**Comment by jan-vince** [comment]
Hi @m49n,

I have added Rainlab.Translate support and removed `trans` function.

Fixed in 1.2.4.

Thanks!
