### ISSUE TITLE
Option to add confirm button with link

### ISSUE THREAD

**Issue by MDRefiner** [jan-vince/smallmessages#4]
And again a very useful great plugin :)
Always having big eyes when there is a new plugin from you. Thank you!

This one will definitely be a must-have in my projects.

What i would love to see (and probably makes sense) is to have an option to add another button next to the „hide/cancel“ button to be able to e.g. inform users about hot news (rainlab.blog record).

Is that maybe on the roadmap?

**Comment by jan-vince** [comment]
Hi @nolyboms and thank you!

I wanted this to be as simple as possible so if you need to customize your message box:

* copy code from eg. `/plugins/janvince/smallmessages/components/messages/messages-modal-b3.htm`
* put it to your theme like this `/themes/[your-theme-name]/partials/messages/default.htm`
* edit code as you like

In Small Messages the default component's HTML code is meant to be just a simple template.
